"""empty message

Revision ID: cf5d1ae9b041
Revises: 
Create Date: 2017-10-06 10:18:38.545495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5d1ae9b041'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pattern_rest_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bidan_id', sa.Integer(), nullable=True),
    sa.Column('pattern_shift', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('latest_rest_schedules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('latest_rest_schedules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bidan_id', sa.INTEGER(), nullable=True),
    sa.Column('pattern_shift', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pattern_rest_schedules')
    # ### end Alembic commands ###
